### PR TITLE
update favicons. closes #57

### LINKED ISSUE #57: upgrade favicons? (5.4+ has removed phantomjs)
Current version of favicon is 6.0, but as of v5.4 favicon no longer depends on phantomjs. Given phantomjs has been deprecated for 2+ years, it would be nice to not be pulling it as a dep anymore. Is there any particular reason the dep is locked to `~5.3.0`, rather than `^5.3.0`?

### PR DESCRIPTION
**Pull request by miguelcobain**
This PR updates the favicons package.
There are a number of reasons for this update, but the main ones I found were:
- newer versions no longer have phantomjs as a transitive dependency. This removes a big burden from `npm install`s and increases compatibility (phantomjs builds aren't available for all architectures)
- newer version supports favicons for more platforms

The second bullet point was actually what made me update the "mocks" for the data we expect. Basically, by default, the package produces more favicons and more html.

It would probably be safer to major bump this package after merging this, since favicons was also major bumped.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@davewasmer ~1 year later, this PR is still pretty much up to date and it would mean a big win for everybody. It's also a very easy win. :)

What can I do to help getting this merged?
Thank you.

**Comment by Exelord** [comment]
Hi Miguel,

Somehow I missed that notification, sorry :/ 

We need to ensure the 6.0 does not bring any breaking change in the config as well. The CI is not setup so that might be also a next step before.
Also we could update it to 6.2.2 to make safe guard against this year issues 😅

**Comment by Exelord** [comment]
Once tests will be green, I'm happy to merge :)

**Comment by miguelcobain** [comment]
@Exelord looks like I need your approval for the github workflow to run.

**Comment by miguelcobain** [comment]
I went ahead and removed the `travis.yaml` file.

**Comment by miguelcobain** [comment]
@Exelord increased timeouts. GH actions are probably slower? 🤷‍♂️ 
Tests are all green locally. Can you approve workflows again, please?

**Comment by miguelcobain** [comment]
Yay. Tests are 💚 .

**Comment by miguelcobain** [comment]
@Exelord my pleasure.
When can we expect a release? 😃

**Pull request merged**
